/*

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
*/

//To Be Modified
import java.util.ArrayList;

public class PentagonalNumber {
    public static ArrayList<Integer> al=new ArrayList<>();
    public static void main(String[] args) {
        for (int i = 1; i < 10; i++) {
            al.add(pen(i));

        }
        System.out.println(isPen(5));
    }

    public static int pen(int n){
        return n*(3*n-1)/2;
    }

    public static boolean isPen(int n){
        return al.contains(n);



    }

}
